Update GH workflow

diff --git a/.github/workflows/tag-and-release.yaml b/.github/workflows/tag-and-release.yaml
--- a/.github/workflows/tag-and-release.yaml
+++ b/.github/workflows/tag-and-release.yaml
@@ -38,8 +38,8 @@ jobs:
       - name: Check if version has changed
         run: |
           if [ "${{ steps.get_version.outputs.VERSION }}" = "${{ steps.get_latest_release.outputs.result }}" ]; then
-            echo "Version has not changed, exiting..."
-            exit 0
+            echo "::error::Version has not changed, exiting..."
+            exit 1
           fi
 
       - name: Install zip
